# Generated by Django 5.0.1 on 2024-01-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepak', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specification',
            field=models.TextField(null=True),
        ),
    ]
