# Generated by Django 5.0.1 on 2024-02-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepak', '0003_category_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
