# Generated by Django 5.0.1 on 2024-02-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepak', '0005_customer_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='product_id',
        ),
        migrations.AddField(
            model_name='customer',
            name='product_url',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
